# name: Generate Snake
# on:
#   schedule:
#     - cron: "0 */12 * * *" # every 12 hours (fixed the cron syntax)
#   workflow_dispatch:
#   push:
#     branches: [ main ] # trigger on push to main branch

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
        
#       - name: Generate github-contribution-grid-snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: DouglasBagambe
#           outputs: |
#             dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#00D4FF&color_dots=#ebedf0,#c6e48b,#7bc96f,#239a3b,#196127
#             dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00D4FF&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            
#       - name: Push github-contribution-grid-snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
